// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/(dashboard)/blog/edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog/edit/[id]">> = Specific
  const handler = {} as typeof import("../../app/admin/(dashboard)/blog/edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/(dashboard)/blog/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog/new">> = Specific
  const handler = {} as typeof import("../../app/admin/(dashboard)/blog/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/(dashboard)/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/blog">> = Specific
  const handler = {} as typeof import("../../app/admin/(dashboard)/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/(dashboard)/comments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/comments">> = Specific
  const handler = {} as typeof import("../../app/admin/(dashboard)/comments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/(dashboard)/forums/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/forums">> = Specific
  const handler = {} as typeof import("../../app/admin/(dashboard)/forums/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/(dashboard)/ingest/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/ingest">> = Specific
  const handler = {} as typeof import("../../app/admin/(dashboard)/ingest/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/(dashboard)/inshorts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/inshorts">> = Specific
  const handler = {} as typeof import("../../app/admin/(dashboard)/inshorts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/(dashboard)/reputation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/reputation">> = Specific
  const handler = {} as typeof import("../../app/admin/(dashboard)/reputation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/(dashboard)/review-queue/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/review-queue">> = Specific
  const handler = {} as typeof import("../../app/admin/(dashboard)/review-queue/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/(dashboard)/stats/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/stats">> = Specific
  const handler = {} as typeof import("../../app/admin/(dashboard)/stats/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/(dashboard)/tutorials/drafts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tutorials/drafts">> = Specific
  const handler = {} as typeof import("../../app/admin/(dashboard)/tutorials/drafts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/(dashboard)/tutorials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tutorials">> = Specific
  const handler = {} as typeof import("../../app/admin/(dashboard)/tutorials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/(dashboard)/videos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/videos">> = Specific
  const handler = {} as typeof import("../../app/admin/(dashboard)/videos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/ask/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ask">> = Specific
  const handler = {} as typeof import("../../app/ask/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]">> = Specific
  const handler = {} as typeof import("../../app/blog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/[slug]/revisions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]/revisions">> = Specific
  const handler = {} as typeof import("../../app/blog/[slug]/revisions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/[slug]/suggest-edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog/[slug]/suggest-edit">> = Specific
  const handler = {} as typeof import("../../app/blog/[slug]/suggest-edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/blog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/blog">> = Specific
  const handler = {} as typeof import("../../app/blog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/forums/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forums/[slug]">> = Specific
  const handler = {} as typeof import("../../app/forums/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/forums/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forums/new">> = Specific
  const handler = {} as typeof import("../../app/forums/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/forums/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/forums">> = Specific
  const handler = {} as typeof import("../../app/forums/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/inshorts/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inshorts/[slug]">> = Specific
  const handler = {} as typeof import("../../app/inshorts/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/inshorts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/inshorts">> = Specific
  const handler = {} as typeof import("../../app/inshorts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/saved/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/saved">> = Specific
  const handler = {} as typeof import("../../app/saved/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/shorts/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shorts/[slug]">> = Specific
  const handler = {} as typeof import("../../app/shorts/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/shorts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/shorts">> = Specific
  const handler = {} as typeof import("../../app/shorts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tags/[tag]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tags/[tag]">> = Specific
  const handler = {} as typeof import("../../app/tags/[tag]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tutorials/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tutorials/[slug]">> = Specific
  const handler = {} as typeof import("../../app/tutorials/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tutorials/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tutorials">> = Specific
  const handler = {} as typeof import("../../app/tutorials/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../app/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/activity/toggle/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/activity/toggle">> = Specific
  const handler = {} as typeof import("../../app/api/admin/activity/toggle/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/autopopulate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/autopopulate">> = Specific
  const handler = {} as typeof import("../../app/api/admin/autopopulate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/blog/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/blog/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/blog/check-duplicate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/check-duplicate">> = Specific
  const handler = {} as typeof import("../../app/api/admin/blog/check-duplicate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/blog/link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/link">> = Specific
  const handler = {} as typeof import("../../app/api/admin/blog/link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/blog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog">> = Specific
  const handler = {} as typeof import("../../app/api/admin/blog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/blog/score/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/blog/score">> = Specific
  const handler = {} as typeof import("../../app/api/admin/blog/score/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/comments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/comments/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/comments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/comments">> = Specific
  const handler = {} as typeof import("../../app/api/admin/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/feed/metrics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/feed/metrics">> = Specific
  const handler = {} as typeof import("../../app/api/admin/feed/metrics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/feed/precompute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/feed/precompute">> = Specific
  const handler = {} as typeof import("../../app/api/admin/feed/precompute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/forums/[id]/feature/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/forums/[id]/feature">> = Specific
  const handler = {} as typeof import("../../app/api/admin/forums/[id]/feature/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/forums/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/forums/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/forums/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/generate-blogs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/generate-blogs">> = Specific
  const handler = {} as typeof import("../../app/api/admin/generate-blogs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/generate-forums/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/generate-forums">> = Specific
  const handler = {} as typeof import("../../app/api/admin/generate-forums/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/jobs/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/jobs/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/jobs/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/jobs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/jobs">> = Specific
  const handler = {} as typeof import("../../app/api/admin/jobs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login">> = Specific
  const handler = {} as typeof import("../../app/api/admin/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/logout">> = Specific
  const handler = {} as typeof import("../../app/api/admin/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/newsletter/digest/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/newsletter/digest">> = Specific
  const handler = {} as typeof import("../../app/api/admin/newsletter/digest/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/observability/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/observability">> = Specific
  const handler = {} as typeof import("../../app/api/admin/observability/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reputation/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reputation/analytics">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reputation/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reputation/recompute/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reputation/recompute">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reputation/recompute/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/reputation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/reputation">> = Specific
  const handler = {} as typeof import("../../app/api/admin/reputation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/review-queue/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/review-queue">> = Specific
  const handler = {} as typeof import("../../app/api/admin/review-queue/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/system/reconciliation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/reconciliation">> = Specific
  const handler = {} as typeof import("../../app/api/admin/system/reconciliation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/system/toggles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/system/toggles">> = Specific
  const handler = {} as typeof import("../../app/api/admin/system/toggles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/tutorials/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tutorials/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/tutorials/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/tutorials/analytics/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tutorials/analytics">> = Specific
  const handler = {} as typeof import("../../app/api/admin/tutorials/analytics/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/tutorials/drafts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tutorials/drafts">> = Specific
  const handler = {} as typeof import("../../app/api/admin/tutorials/drafts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/tutorials/reorder/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tutorials/reorder">> = Specific
  const handler = {} as typeof import("../../app/api/admin/tutorials/reorder/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/tutorials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tutorials">> = Specific
  const handler = {} as typeof import("../../app/api/admin/tutorials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/videos/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/videos/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/admin/videos/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/videos/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/videos">> = Specific
  const handler = {} as typeof import("../../app/api/admin/videos/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[...nextauth]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[...nextauth]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[...nextauth]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog/[slug]/ask-ai/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]/ask-ai">> = Specific
  const handler = {} as typeof import("../../app/api/blog/[slug]/ask-ai/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog/[slug]/comments/[commentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]/comments/[commentId]">> = Specific
  const handler = {} as typeof import("../../app/api/blog/[slug]/comments/[commentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog/[slug]/comments/[commentId]/vote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]/comments/[commentId]/vote">> = Specific
  const handler = {} as typeof import("../../app/api/blog/[slug]/comments/[commentId]/vote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog/[slug]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]/comments">> = Specific
  const handler = {} as typeof import("../../app/api/blog/[slug]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog/[slug]/downvote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]/downvote">> = Specific
  const handler = {} as typeof import("../../app/api/blog/[slug]/downvote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog/[slug]/revisions/[revisionId]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]/revisions/[revisionId]/approve">> = Specific
  const handler = {} as typeof import("../../app/api/blog/[slug]/revisions/[revisionId]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog/[slug]/revisions/[revisionId]/reject/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]/revisions/[revisionId]/reject">> = Specific
  const handler = {} as typeof import("../../app/api/blog/[slug]/revisions/[revisionId]/reject/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog/[slug]/revisions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]/revisions">> = Specific
  const handler = {} as typeof import("../../app/api/blog/[slug]/revisions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog/[slug]/share/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]/share">> = Specific
  const handler = {} as typeof import("../../app/api/blog/[slug]/share/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog/[slug]/suggest-edit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]/suggest-edit">> = Specific
  const handler = {} as typeof import("../../app/api/blog/[slug]/suggest-edit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog/[slug]/upvote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]/upvote">> = Specific
  const handler = {} as typeof import("../../app/api/blog/[slug]/upvote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog/[slug]/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/[slug]/view">> = Specific
  const handler = {} as typeof import("../../app/api/blog/[slug]/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/blog/feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/blog/feed">> = Specific
  const handler = {} as typeof import("../../app/api/blog/feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/cover-image/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/cover-image">> = Specific
  const handler = {} as typeof import("../../app/api/cover-image/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/feed/events/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/feed/events">> = Specific
  const handler = {} as typeof import("../../app/api/feed/events/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/forums/[slug]/best-answer/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forums/[slug]/best-answer">> = Specific
  const handler = {} as typeof import("../../app/api/forums/[slug]/best-answer/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/forums/[slug]/comments/[commentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forums/[slug]/comments/[commentId]">> = Specific
  const handler = {} as typeof import("../../app/api/forums/[slug]/comments/[commentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/forums/[slug]/comments/[commentId]/vote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forums/[slug]/comments/[commentId]/vote">> = Specific
  const handler = {} as typeof import("../../app/api/forums/[slug]/comments/[commentId]/vote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/forums/[slug]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forums/[slug]/comments">> = Specific
  const handler = {} as typeof import("../../app/api/forums/[slug]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/forums/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forums/[slug]">> = Specific
  const handler = {} as typeof import("../../app/api/forums/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/forums/[slug]/vote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forums/[slug]/vote">> = Specific
  const handler = {} as typeof import("../../app/api/forums/[slug]/vote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/forums/ai-improve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forums/ai-improve">> = Specific
  const handler = {} as typeof import("../../app/api/forums/ai-improve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/forums/blog-link/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forums/blog-link">> = Specific
  const handler = {} as typeof import("../../app/api/forums/blog-link/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/forums/feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forums/feed">> = Specific
  const handler = {} as typeof import("../../app/api/forums/feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/forums/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/forums">> = Specific
  const handler = {} as typeof import("../../app/api/forums/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/generate-blog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-blog">> = Specific
  const handler = {} as typeof import("../../app/api/generate-blog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/generate-bulk-blogs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/generate-bulk-blogs">> = Specific
  const handler = {} as typeof import("../../app/api/generate-bulk-blogs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ingest/[jobId]/publish/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ingest/[jobId]/publish">> = Specific
  const handler = {} as typeof import("../../app/api/ingest/[jobId]/publish/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ingest/[jobId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ingest/[jobId]">> = Specific
  const handler = {} as typeof import("../../app/api/ingest/[jobId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ingest/document/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ingest/document">> = Specific
  const handler = {} as typeof import("../../app/api/ingest/document/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/ingest/url/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ingest/url">> = Specific
  const handler = {} as typeof import("../../app/api/ingest/url/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leaderboard">> = Specific
  const handler = {} as typeof import("../../app/api/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/me/reputation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/reputation">> = Specific
  const handler = {} as typeof import("../../app/api/me/reputation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/newsletter/subscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/newsletter/subscribe">> = Specific
  const handler = {} as typeof import("../../app/api/newsletter/subscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/newsletter/unsubscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/newsletter/unsubscribe">> = Specific
  const handler = {} as typeof import("../../app/api/newsletter/unsubscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notifications/read/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications/read">> = Specific
  const handler = {} as typeof import("../../app/api/notifications/read/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/notifications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/notifications">> = Specific
  const handler = {} as typeof import("../../app/api/notifications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reputation/[identityKey]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reputation/[identityKey]">> = Specific
  const handler = {} as typeof import("../../app/api/reputation/[identityKey]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reputation/history/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reputation/history">> = Specific
  const handler = {} as typeof import("../../app/api/reputation/history/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/reputation/leaderboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/reputation/leaderboard">> = Specific
  const handler = {} as typeof import("../../app/api/reputation/leaderboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shorts/[slug]/like/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shorts/[slug]/like">> = Specific
  const handler = {} as typeof import("../../app/api/shorts/[slug]/like/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shorts/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shorts/[slug]">> = Specific
  const handler = {} as typeof import("../../app/api/shorts/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shorts/[slug]/view/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shorts/[slug]/view">> = Specific
  const handler = {} as typeof import("../../app/api/shorts/[slug]/view/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shorts/feed/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shorts/feed">> = Specific
  const handler = {} as typeof import("../../app/api/shorts/feed/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/shorts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/shorts">> = Specific
  const handler = {} as typeof import("../../app/api/shorts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/trending/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/trending">> = Specific
  const handler = {} as typeof import("../../app/api/trending/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tutorials/[slug]/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tutorials/[slug]/progress">> = Specific
  const handler = {} as typeof import("../../app/api/tutorials/[slug]/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tutorials/[slug]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tutorials/[slug]">> = Specific
  const handler = {} as typeof import("../../app/api/tutorials/[slug]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tutorials/progress/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tutorials/progress">> = Specific
  const handler = {} as typeof import("../../app/api/tutorials/progress/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/tutorials/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tutorials">> = Specific
  const handler = {} as typeof import("../../app/api/tutorials/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/mentions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/mentions">> = Specific
  const handler = {} as typeof import("../../app/api/users/mentions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/preferences/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/preferences">> = Specific
  const handler = {} as typeof import("../../app/api/users/preferences/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/profile">> = Specific
  const handler = {} as typeof import("../../app/api/users/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users">> = Specific
  const handler = {} as typeof import("../../app/api/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/sitemap-news.xml/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/sitemap-news.xml">> = Specific
  const handler = {} as typeof import("../../app/sitemap-news.xml/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/forums/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/forums">> = Specific
  const handler = {} as typeof import("../../app/forums/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
